services:
  ui:
    build: ./frontend/
    container_name: frontend
    depends_on:
      - database
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/frontend
      

  backend: 
    build: ./backend/
    container_name: backend
    depends_on:
      - database
    ports:
      - 8080:8080
    volumes:
      - ./backend:/backend
      
  database:
    image: postgres:latest
    container_name: database
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "docker"
      POSTGRES_DB: 'inventory_management_system'
    ports:
      - 5432:5432